name: deploy on push
on: [push]
   
jobs:
    deploy-app:
      runs-on: ubuntu-latest
      steps:
        - name: check out the code to build server
          uses: actions/checkout@v3    
        - name: copy file to server
          uses: appleboy/scp-action@master
          with:
           host: ${{101.200.125.150}}
           username: ${{secrets.root}}
           port: ${{secrets.22}}
           key: ${{secrets.MIIEpAIBAAKCAQEApO6hgk8ssvhplAVAr8lf+z4Ntt6ATHTBCJnzAZPZitQ2nAU5/6z2BRx1dPR41zk4cZuDit6b7IWmwiqrNPEYZwfZdEPttPCZ7oxhlDEGlV3Ryu7X2AVSHVQUHY66ttnMwQCs0waQDQjhMa9O9wO5BvNDFftHGNefiBajdoEOuFOycb6/TS11LX/nlDrCT62zKsL9RtyCkF1Z4l0/qsgqOzTs0FDHk9PA8KXJ2NV+EVEfiLcmNkuhMWzrNm+9+1eEwe4IPjoai01BGVcN4ZTb5+5rX0oqV6VaIc5gKLkYNSD3wS4TZgE3Ca+IvyV5JOBPLPI28t95fN2csJec3AmEWQIDAQABAoIBAQCRfmUBhAClfJf+WMfgil9eTjZg7FT3nUMv6EbDTH7qhhwKdF3emuCIT7uZyZPUIIkXRx26YnfgJWKfBG71i/1/3h/I/adzJ5BTLIlj5f+twg6w2xOTX9Y5QxNfo6o4ZVfHpmXO3ooyxXOKleCt7R3K8MtsV7c3RfdYYMggYObwWIwOKAczdMxZUfh1DLBWlzRAXP8oE1GxEiVfLfsA8z4KjG3yFWJXvZk6z1gZi9LwYZfvwNtbsl9mXOH8S6slwpb448elnqwLsTCxuRPUKCyHTZo2GEIfi0+y/o8bB1Sz5tgBlndTQdhhjzUWZe9GS/dyInjpo4jvnAeFz8qfys91AoGBAPhkmWc17qFBxhnmRfCJBguxR/x9kYj21v1zkA636NuY9jVdHgKhMPKYrCFOpxOF+sOGlL/9CsA/oIvbsIQpkRI4ly0VU6GjMJ2qM0gJ+ppHq6OQkfdQ5XDrayOqiz4bzeds5bl4pd6QjgA6RC+LWIrwRYS8e1C6ebv4frReAAlbAoGBAKn7suvTp8YgeLdaZMFA7eExIQ/vNVTlWzQAyx45BCl6kB67gdpO6asm574nVplJPLgvmSjeyyh0YF2qpgqdQ4zobuTJ/xkoK/U0CO1rU8/D05gERUEoPv7Z4BFMhDEPjcD7EXYYaQH+37GhidSEH70yKIXBECkeDALTJ+UvuGNbAoGAaMzxGGXd5/W7YoQQsDrv7REAYVyNge87qDYQ6tTXj4eLIdrG5a8i2shln6vyvD8EHWjz68kUtyZhU4D+idSL29c6mY/s+D7FLVB5UIS9Uki490rw+xsLo0gArUywcSUEDAebKVTpDu2IrDnpOPIfCofznNx1Xws+f3uJ4gnjFA8CgYBHpKRGrRCbevgmH10z7o/USAatVp7dx0VnZ6Y0eMd+TAAOU+1o+7WUw3MNPDtNpAaJgtZE2ZI63MH4+IG/G4VrEFQc7d4s1jegw2u31XKfsOOvwK0Hx1S1yVKdN+jHXMzcN3Wmlqc7hhb2ISWcgot2DHvz0+lhyx442pKIEFLg3QKBgQDiSnszO4HP2PkOwr1RKzygbT+uIp2KipOHO2MR7t32Z9MyCb+CxeSAxxC9FZ9NTjbvJrSbkh55K17kOBbhglMxfzqo7uvuC2J0e5w3BYozgfeNZMGnDYX12o/1vK3Mqb2277I8Eu+vLPgciTTRUtmTNID2lMW6yX1ax8huuqh0iQ==}}
           source: "./html/*"
           target: "/var/www/html"
           strip_components: 1
